/**
 * Stable UI / client error keys — keep copy in errorMessages.ts (DRY).
 */
export enum ClientErrorCode {
  LOAD_MATCHES = 'LOAD_MATCHES',
  LOAD_MATCH_DETAILS = 'LOAD_MATCH_DETAILS',
  LOAD_SCORECARD = 'LOAD_SCORECARD',
  LOAD_COMMENTARY = 'LOAD_COMMENTARY',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  NETWORK_UNREACHABLE = 'NETWORK_UNREACHABLE',
  REQUEST_FAILED = 'REQUEST_FAILED',
  GENERIC_TITLE = 'GENERIC_TITLE',
  MATCH_NOT_FOUND = 'MATCH_NOT_FOUND',
  FETCHING_MATCHES = 'FETCHING_MATCHES',
  LOADING_MATCH_DETAILS = 'LOADING_MATCH_DETAILS',
  NO_MATCHES_TITLE = 'NO_MATCHES_TITLE',
  SCORECARD_UNAVAILABLE_TITLE = 'SCORECARD_UNAVAILABLE_TITLE',
  SCORECARD_UNAVAILABLE_BODY = 'SCORECARD_UNAVAILABLE_BODY',
  SCORECARD_EMPTY_TITLE = 'SCORECARD_EMPTY_TITLE',
  SCORECARD_EMPTY_BODY = 'SCORECARD_EMPTY_BODY',
  COMMENTARY_UNAVAILABLE_TITLE = 'COMMENTARY_UNAVAILABLE_TITLE',
  COMMENTARY_UNAVAILABLE_BODY = 'COMMENTARY_UNAVAILABLE_BODY',
  COMMENTARY_EMPTY_TITLE = 'COMMENTARY_EMPTY_TITLE',
  COMMENTARY_EMPTY_BODY = 'COMMENTARY_EMPTY_BODY',
  REFRESH_HINT = 'REFRESH_HINT',
  YET_TO_BAT = 'YET_TO_BAT',
}
